= Python

== Was ist Python

Python ist eine Programiersprache,die mit ihrer klaren Syntax und einfache Lesberkeit leicht zu erlearnen ist und kann vielseitig eingesetzt werden.

=== Python in Nano und Vi

Auf beiden Editoren kann man Python Skripte schreiben

=== Start in Python

[source,bash]
.Man erstellen erstmal eine Datie die file1.py heißt

----
touch file1.py 
----

oder

----
> file1.py
----

[source,bash]
.Um file1.py Ausführbar zu machen benutzen wir:
----
chmod a+x file1.py
----
-> chmod steht für change mode

=== In vi oder nano

Man benutzt als erstes den shebang (Shebang bezeichnet die Zeichenkombination #! am Anfang eines Skriptprogramms, ähnlich einer Dokumenttypdefinition. Bei unixoiden Betriebssystemen führt die Markierung mit Doppelkreuz und Ausrufezeichen dazu, dass das folgende Kommando mitsamt allen angegebenen Argumenten beim Aufruf des Programms ausgeführt wird. Der Dateiname wird dann als weiteres Argument übergeben.)<1>

<1> https://de.wikipedia.org/wiki/Shebang 

[source,bash]
.shebang
----
#!/usr/bin/python3
----

=== So macht man Eirückungen

Benutzen Sie auf keinen Fall ein Mischmasch von Tabulatoren und Leerzeichen zur Einrückung, weil es nicht sauber plattformübergreifend funktioniert, da die Breite eines Tabulators in Leerzeichen nicht eindeutig für alle Plattformen definiert ist. Meine eindringliche Empfehlung ist, dass Sie entweder einen einzelnen Tabulator oder zwei oder vier Leerzeichen pro Einrückungs-Ebene benutzen.

*benutzen Sie ausschließlich einen Einrückungsstil*


== Erstes Programm

* Eine Datei erstellen,zum Beispiel file1.py
* Datei öffnen mit einem Editor wie zum Beispiel dem vi oder dem nano
* Datei editieren

[source,bash]
.Die shebang kommt immer zuerst
----
#!/usr/bin/python3

print("Hallo Welt")
----

* Ausgabe

_Hallo Welt_


[source,bash]
.programm 2

----
#!/usr/bin/python3

ausgabe = "wert"
anzahl = 2 
anzahl = 3 
# michgibtsnicht = "irgendwas"

print("Hallo Welt")
print(ausgabe)
print(anzahl*3)
print("anzahl"*3)

print(michgibtsnicht)
----

->Ausgabe

Hallo Welt
wert
9
anzahlanzahlanzahl
Traceback (most recent call last):
  File "/home/suleiman/bin/file1.py", line 13, in <module>
    print(michgibtsnicht)
NameError: name 'michgibtsnicht' is not defined

* so haben wir unser erstes fehler ausgelöst

== Bedingte Anweisungen

Die if-Anweisung wird benutzt um programmablauefe zu steurn(ob bestimmte programmteile ausgeführt werden oder nicht ).

Wenn Sie mehrere Bedingungen nutzen möchten, verwenden Sie bei der erstes Bedingung zwar "if", bei allen weiteren am Anfang jedoch "elif".

Falls keine der Bedingungen zutrifft, werden die Befehle, die unter "else:" stehen, ausgeführt.

[source,bash]

._Beispiel_
----
#!/usr/bin/python3

var = 5 
var = True
var = False
var = None


# Kommentar
if var is False:
    print("falsch")
elif var is True:
    print("richtig")
elif var is None:
    print("nichts")
else:
    print("was anderes")
    

print('Ende Gelände')
----

->Ausgabe

----
nichts
Ende Gelände
----

* da die letzte var = None wird halt "nichts" ausgedrückt
  dan kommt die normale print am ende "Ende Gelände"

== Schleifen

Schleifen, werden benötigt, um einen Codeblock wiederholt auszuführen. Die meisten Schleifen enthalten einen Zähler oder ganz allgemein Variablen, die vor der schleife oder innerhalb ihr berechnugen durchführen.

[source,bash]
.Im folgenden sehen wir die allgemeine Syntax der for-Schleife in Python. <teilnehmer> steht für eine Liste, ein Tupel oder ein Dictionary

----
#!/usr/bin/python3

teilnehmer = [
    {'first': 'Erna', 'last': 'Mayer'},
    {'first': 'Fred', 'last': 'Tischler'},
    {'first': 'Karsten', 'last': 'Schmidt'}] <1>
first = 'first'
x = 0
for item in teilnehmer:
    x = x + 1 # da es in eine schleife ist zählt es immer weiter 1,2,3...
    print(x) 
    print(item['last']) # mit ['last'] werd der nachname von der liste auslesen
    print(item['first']) # mit ['first'] werd der vorname von der liste ausgelesen
    print(item) # die gesamte dic
    print(item[first]) # wenn man eine variable die first heisst da dann musste man oben first = "first" hinschreiben
    print('-'*10)
----

<1> https://www.python-kurs.eu/python3_dictionaries.php

=== if in eine schleife:

[source,bash]
.Beispiel zu if in eine schleife, plus input
----
#!/usr/bin/python3


obst = ['Apfel', 'Banane', 'Birne', 'Kiwi']

eingangsfrage = input('Soll ueberhaupt etwas ausgegeben werden? [J|N]: ')

if eingangsfrage == 'j' or eingangsfrage == 'J' or eingangsfrage == 'y' or eingangsfrage == 'Y':
    for frucht in obst:
        frage = input('Soll die Frucht ausgegeben werden? [J|N]: ')
    #    if frage == 'J':
    #        print(frucht)
    #    elif frage == 'j':
    #        print(frucht)
    
        if frage == 'j' or frage == 'J' or frage == 'y' or frage == 'Y':
            print(frucht)
----

==== Was is input?

Der Eingabestring des Benutzers wird von input() interpretiert, d.h. input() liefert beispielsweise einen Integer Wert zurück, wenn der Benutzer eine ganze Zahl eingeben hat und eine Liste, wenn der Benutzer eine Liste eingegeben hat.

[source,bash]
.Beispiel
----
eingangsfrage = input('Soll ueberhaupt etwas ausgegeben werden? [J|N]: ')
----

Achte auf größ klein schreibung

==== continue/break

-Eine break in einem Schleifencode bewirkt dass an dieser Stelle mit sofortiger Wirkung die sie unmittelbar umgebende Schleife verlassen wird.
-Die continue Anweisung bewirkt dass an dieser Stelle wieder in den Schleifenkopf “gesprungen” und die nächste Prozess ausgeführt wird. Der noch folgende Teil des Schleifenrumpfs wird nicht mehr ausgeführt.

[source,bash]
.Beispiel
----
#!/usr/bin/python3


obst = ['Apfel', 'Banane', 'Birne', 'Kiwi']

#eingangsfrage = input('Soll ueberhauptnichts etwas ausgegeben werden? [J|N]: ')

for frucht in obst:
#    if eingangsfrage == 'j' or eingangsfrage == 'J' or eingangsfrage == 'y' or eingangsfrage == 'Y':
##        break
#        continue

#################################
    if frucht == 'Birne':
        continue
#################################

    frage = input('Soll die Frucht ausgegeben werden? [J|N]: ')
#    if frage == 'J':
#        print(frucht)
#    elif frage == 'j':
#        print(frucht)

    if frage == 'j' or frage == 'J' or frage == 'y' or frage == 'Y':
        print(frucht)
----

=== Parameterübergabe: Parameter und Argumente

Eine Funktion oder eine Prozedur benötigt üblicherweise Information über die Umgebung aus der heraus sie aufgerufen worden ist. Die Schnittstelle zwischen dieser Umgebung und der Funktion bzw. Prozedur, d.h. dem Funktionsrumpf (body) bzw. Prozedurrumpf, besteht aus speziellen Variablen, die man als Parameter bezeichnet. Indem man Parameter benutzt, kann man verschiedenste Objekte von "außen" innerhalb der Funktion benutzen. Die Syntax, wie man Parameter deklariert, und die Semantik, wie man die Argumente des Aufrufs an die formalen Parameter der Funktion oder Prozedur weiterleitet sind abhängig von der jeweiligen Programmiersprache.

Im vorigen Abschnitt haben wir mehrfach die Begriffe Parameter und Argumente verwendet. Bei einigen Lesern hat sich sicherlich der Eindruck eingestellt, dass die beiden Begriffe synonym sind. Auch in der Literatur werden diese Begriffe häufig synonym verwendet. Dennoch gibt es einen klar definierten Unterschied. Parameter stehen im Kopf der Funktion oder Prozedur, also in der Definition der Funktion oder Prozedur. Während Argumente beim Aufruf verwendet werden. Sie liefern die Werte für die formalen Parameter während der Laufzeit des Programmes. <2>


<2> https://www.python-kurs.eu/python3_parameter.php


