= Python

== Was ist Python

Python ist eine Programiersprache,die mit ihrer klaren Syntax und einfache Lesberkeit leicht zu erlearnen ist und kann vielseitig eingesetzt werden.

=== Python in Nano und Vi

Auf beiden Editoren kann man Python Skripte schreiben

=== Start in Python

[source,bash]
.Man erstellen erstmal eine Datie die file1.py heißt

----
touch file1.py 
----

oder

----
> file1.py
----

[source,bash]
.Um file1.py Ausführbar zu machen benutzen wir:
----
chmod a+x file1.py
----
-> chmod steht für change mode

=== In vi oder nano

Man benutzt als erstes den shebang (Shebang bezeichnet die Zeichenkombination #! am Anfang eines Skriptprogramms, ähnlich einer Dokumenttypdefinition. Bei unixoiden Betriebssystemen führt die Markierung mit Doppelkreuz und Ausrufezeichen dazu, dass das folgende Kommando mitsamt allen angegebenen Argumenten beim Aufruf des Programms ausgeführt wird. Der Dateiname wird dann als weiteres Argument übergeben.)<1>

<1> https://de.wikipedia.org/wiki/Shebang 

[source,bash]
.shebang
----
#!/usr/bin/python3
----

=== So macht man Eirückungen

Benutzen Sie auf keinen Fall ein Mischmasch von Tabulatoren und Leerzeichen zur Einrückung, weil es nicht sauber plattformübergreifend funktioniert, da die Breite eines Tabulators in Leerzeichen nicht eindeutig für alle Plattformen definiert ist. Meine eindringliche Empfehlung ist, dass Sie entweder einen einzelnen Tabulator oder zwei oder vier Leerzeichen pro Einrückungs-Ebene benutzen.

*benutzen Sie ausschließlich einen Einrückungsstil*


== Erstes Programm

* Eine Datei erstellen,zum Beispiel file1.py
* Datei öffnen mit einem Editor wie zum Beispiel dem vi oder dem nano
* Datei editieren

[source,bash]
.Die shebang kommt immer zuerst
----
#!/usr/bin/python3

print("Hallo Welt")
----

* Ausgabe

_Hallo Welt_


[source,bash]
.programm 2

----
#!/usr/bin/python3

ausgabe = "wert"
anzahl = 2 
anzahl = 3 
# michgibtsnicht = "irgendwas"

print("Hallo Welt")
print(ausgabe)
print(anzahl*3)
print("anzahl"*3)

print(michgibtsnicht)
----

->Ausgabe

Hallo Welt
wert
9
anzahlanzahlanzahl
Traceback (most recent call last):
  File "/home/suleiman/bin/file1.py", line 13, in <module>
    print(michgibtsnicht)
NameError: name 'michgibtsnicht' is not defined

* so haben wir unser erstes fehler ausgelöst



