= Python

== Was ist Python

Python ist eine Programiersprache,die mit ihrer klaren Syntax und einfacher Lesberkeit, leicht zu erlearnen ist und kann vielseitig eigesaetzt werden.

=== Python in Nano und Vi

Auf beiden Editoren kann man Python Skripte schreiben

=== Start in Python

[source,bash]
.Man erstellt erstmal eine Datie die file1.py heißt

----
touch file1.py 
----

oder

----
> file1.py
----

[source,bash]
.Um file1.py ausführbar zu machen benutzt man:
----
chmod a+x file1.py
----
-> chmod steht für change mode

=== In vi oder nano
Man benutzt als erstes den shebang (Shebang bezeichnet die Zeichenkombination #! am Anfang eines Skriptprogramms, ähnlich einer Dokumenttypdefinition. Bei unixoiden Betriebssystemen führt die Markierung mit einem Doppelkreuz und Ausrufezeichen dazu, dass das folgendes Kommando mitsamt allen angegebenen Argumenten beim Aufruf des Programms ausgeführt wird. Der Dateiname wird dann als weiteres Argument übergeben.)<1>

<1> https://de.wikipedia.org/wiki/Shebang 

[source,bash]
.shebang
----
#!/usr/bin/python3
----

== Erstes Programm

* Eine Datei erstellen, zum Beispiel file1.py
* Datei öffnen mit einem Editor wie zum Beispiel dem vi oder dem nano
* Datei editieren

[source,bash]
.Die shebang kommt immer zuerst
---
#!/usr/bin/python3

print("Hallo Welt")
----

* Ausgabe

_Hallo Welt_



















